### PR TITLE
New flag --document-dependency-values

### PR DESCRIPTION
**Pull request by armsnyder**
## Features

Adds new CLI flag `-u/--document-dependency-values` for documenting values from dependencies, recursively.

The flag is disabled by default, so it should not affect existing behavior.

Relates to #70 ; however it only supports local dependencies for now since it relies on the existing parsing logic.

## Bug fixes

**This change also includes two drive-by bug fixes.**

* Replace usages of `path.Join` with `filepath.Join` when joining directories, for better cross-platform support.
* Fix a `FileSortOrder` sorting bug in `model.go` where it would not sort by line due to an incorrect `valuesTableRows[i].LineNumber < valuesTableRows[i].LineNumber` comparison operation.

## Details

I added a new example chart called `umbrella` and ran the helm-docs command on it using `--document-dependency-values` to illustrate the change.

In `main.go`, instead of parsing and printing on the same pass, I changed it to parse first and print second. This let me reference values files from dependencies which were already parsed. Both passes use parallel processing, as before.

### CODE REVIEW

**Comment by LtChae** [comment]
My team has umbrella charts as well that would benefit from this change. Definitely interested in seeing this merged.

**Comment by dirien** [comment]
Thats cool! I think about to ask @norwoodj to allow additional maintainers to help to improve this project.

**Comment by norwoodj** [comment]
I apologize for my slowness, I have not been very good at keeping up with pull requests here. I will try to take a look soon.

**Comment by armsnyder** [comment]
Thanks! I'll resolve conflicts on this today.

**Comment by armsnyder** [comment]
@norwoodj I rebased my branch. I saw that the `PrintDocumentation` function signature was modified in a breaking way recently. I assume we don't care about making breaking Go package changes, so I'm changing my own argument which was previously `...DependencyValues` (non-breaking) to `[]DependencyValues` (breaking).

**Comment by norwoodj** [comment]
Merged. Thanks a ton for the contribution and sorry again for being so slow to review it.

**Pull request merged**
