### PR TITLE
Customize default values with doc string

### PR DESCRIPTION
**Pull request by Grannath**
Solves #22 

This allows to use the discussed format to override the default values. It also allows comments to continue on the next line.

### CODE REVIEW

**Comment by eddycharly** [comment]
@Grannath this is a good starting point. Just a few improvements to make it more robust and it should be great.

**Comment by merlindorin** [comment]
Bump, seems promising

**Comment by eddycharly** [comment]
@Grannath are you still interested in working on this ?

If you don't have time, no worries. Just tell so that i can go ahead and work on it.

**Comment by Grannath** [comment]
@eddycharly Hey, sorry. I switched jobs in the meantime. I'm not used to Go, so I don't mind if you want to take over. Hope it helped as a start.

**Comment by eddycharly** [comment]
@Grannath sorry, i missed your reply. This is quite a good starting point, thanks for initiating it !
I will try to come up with something next week.

**Comment by eddycharly** [comment]
@norwoodj i opened a PR here https://github.com/norwoodj/helm-docs/pull/29 based on @Grannath work with a few improvements.

Thanks to both of you.

**Comment by norwoodj** [comment]
This has been fixed by @eddycharly's work. Closing now

**Pull request closed without merging**
