### PR TITLE
Issue 169: Introduce strict linting options of values and exclusions

### PR DESCRIPTION
**Pull request by edmondop**
This PR introduce three options for the helm-docs executable:
- an option to fail if there are some values with no documentation
- an option to ignore some values without documentation by regex
- an option to ignore some values without documentation by name

Addresses #169

### CODE REVIEW

**Comment by edmondop** [comment]
Ping @Nepo26

**Comment by Nepo26** [comment]
Hey, I looked into it and found just one issue with validation. I'll comment it later today.

> OBS.: Sorry by the late response. I had some problems on the latest weeks.

**Review by Nepo26 — CHANGES_REQUESTED** [review]
Take a look on this change. I think it's a specific case but can happen sometimes.

**Comment by Nepo26** [comment]
Hey @edmondop I did some changes if you can take a look if it makes sense. Basically made some parts of the GitHub workflow more updated and improved the part about the _PROJECT_ROOT_, so it becomes prettier.

**Comment by edmondop** [comment]
> Hey @edmondop I did some changes if you can take a look if it makes sense. Basically made some parts of the GitHub workflow more updated and improved the part about the _PROJECT_ROOT_, so it becomes prettier.

Thank you, makes sense!

**Review by Nepo26 — APPROVED** [review]
Everything ok then. Again sorry by my lateness.

I will approve it and proceed with publishing.

**Pull request merged**
