### PR TITLE
explicitly document lists and maps when there are elements defined inside of them

### PR DESCRIPTION
**Pull request by charliesignalfx**
Hi,
Currently when there is a map or a list that has values inside of it, the list/map is not documented.  In my values.yaml I have lists that have default elements defined inside, but these lists could still be extended by the user.  For this reason I still want the documentation for the list itself to be included.  This pr adds this functionality.  If you would like I could try to put this functionality behind a couple of run time flags?  

Thank you for writing this awesome tool!

Example:
```yaml
# exampleObj -- this is an example object that I would like documented
exampleObj:
  # exampleObj.key -- this is a specific key on the object I would also like documented
  key: value
# exampleList -- this is an example list
exampleList:
    # exampleList[0] -- the first element in the list
    # exampleList[0].objectInList -- this is an object inside of the list
  - objectInList:
    # exampleList[0].name -- this is an element on the object inside of the list
    name: "object in list"
```
currently helm-docs generates:

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| exampleList[0].name | string | "object in list" | this is an element on the object inside of the list |
| exampleList[0].objectInList | string | \<nil\> | this is an object inside of the list |
| exampleObj.key | string | "value" | this is a specific key on the object I would also like documented |

this pr will generate:

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| exampleList | list | [] | this is an example list |
| exampleList[0] | object | {} | the first element in the list |
| exampleList[0].name | string | "object in list" | this is an element on the object inside of the list |
| exampleList[0].objectInList | string | \<nil\> | this is an object inside of the list |
| exampleObj | object | {} | this is an example object that I would like documented |
| exampleObj.key | string | "value" | this is a specific key on the object I would also like documented |

### CODE REVIEW

**Comment by norwoodj** [comment]
Thanks for the PR @charliesignalfx ! I have been thinking about implementing something like this for some time. I don't know that this is exactly the way I want to go, mostly because I worry that documenting every key as we recurse downwards will simply get too verbose. What I am thinking instead is the following:

* Only leaf nodes  (empty lists, empty objects, strings, ints, and floats) are automatically documented
* If a list or object has a comment with a description, document it as a value, as you have done here. The `default` field for lists and objects in this case should be a jsonified string of the field
* Documenting a list or object in the above fashion stops the automatic documentation of contained fields, that is, they will not be added to the values table. However, if a contained field has a description comment on it, then it _will_ then be included.

An example:
```
exampleObjectNoDescriptions:
  key: value

exampleListNoDescriptions:
  - key: value

# exampleObjectDescription -- this object will be documented
exampleObjectDescription:
  keyNoDescription: value

  # exampleObjectDescription.keyWithDescription -- this object key will be documented
  keyWithDescription: value

# exampleListDescription -- this list will be documented
exampleListDescription:
  - keyNoDesciption: value

  # exampleListDescription[1].keyWithDescription -- this list item key will be documented
  - keyWithDescription: value

  # exampleListDescription[2] -- this list item will be documented
  - listItemWithDescription: value
```
Produces

| Key | Type | Default | Description |
|-----|------|--------|-------------|
| exampleObjectNoDescriptions.key | string | "value" | |
| exampleListNoDesciptions[0].key | string | "value" | |
| exampleObjectDescription | object | `{"keyNoDescription": "value", "keyWithDescription": "value"}` | this object will be documented |
| exampleObjectDescription.keyWithDescription | string | "value" | this object key will be documented |
| exampleListDescription | list | `[{"keyNoDescription": "value"}, {"keyWithDescription": "value"}, {"listItemWithDescription": "value"}]` | this list will be documented |
| exampleListDescription[1].keyWithDescription | string | "value" | this list item key will be documented |
| exampleListDescription[2] | object | `{"listItemWithDescription": "value"}` | this list item will be documented |

Note how `exampleListDescription.keyNoDesciption` and `exampleObjectDescription.keyNoDescription` aren't documented because the containing object and list themselves have description comments, but the other contained keys are documented because they _do_ have description comments.

Does this meet your needs? I like this better because it's closer in line to what the [stable charts folks](https://github.com/helm/charts/tree/master/stable/grafana#configuration) do in a lot of their documentation, and I think it's very flexible. I would definitely like to hear from you though if this is how you would like the feature to behave.

This is a fairly involved feature, and so I can make time to implement it myself in the near future if you don't want to put in that much work. Please let me know.

**Comment by charliesignalfx** [comment]
Hi @norwoodj,
Thank you for your response.  This sounds exactly like the behavior I would like.  I unfortunately don't have time at the moment to implement it for at least a few weeks.  So if you are able to get to it sometime in the near future, I would really appreciate the changes you've proposed.

**Comment by norwoodj** [comment]
Glad to hear that this is an agreeable behavior. This feature actually sounded kinda fun to implement... so I've started.

You can follow the progress on this [issue](https://github.com/norwoodj/helm-docs/issues/9).

Thanks for the feature request, I wasn't sure if this was actually something people would want.

**Comment by norwoodj** [comment]
@charliesignalfx, I have implemented the feature as described above as part of this [PR](https://github.com/norwoodj/helm-docs/pull/10), and updated the README documentation in this repo to reflect the new logic. Please let me know if anything is unclear, or not what you were expecting. Thanks again for the feature request and PR. Hope you enjoy helm-docs!

I will close this PR now, as I believe the feature is implemented in a way that is hopefully satisfactory

**Pull request closed without merging**
