### PR TITLE
fix: change go mod to not break on go build

### LINKED ISSUE #202: [Bug]: building for openSUSE fails with "unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am packaging this very helpful utility for openSUSE. Currently it fails due to the following error:

```
[    4s] + go build -mod=vendor -buildmode=pie -o bin/helm-docs ./cmd/helm-docs
[    5s] # golang.org/x/sys/unix
[    5s] vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
[    5s] vendor/golang.org/x/sys/unix/syscall_linux.go:1018:20: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
[    5s] vendor/golang.org/x/sys/unix/syscall_linux.go:2297:9: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
[    5s] vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
[    5s] vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.KYRhIP (%build)
```

The go.mod file still states go1.14 as required, I guess this should be increased to go1.17?

(Just changing that one line in the file during build solves this error, but then leads to error due to the vendoring necessary for building without internet connnectivity)

### Expected Behavior

Successful build.

### Reference Chart

None, no runtime problem.

### Reference Template

_No response_

### Environment

Building on openSUSE 64bit

### Link to `helm-docs` Logs

_No response_

### Further Information

_No response_

### PR DESCRIPTION
**Pull request by Nepo26**
Seems to fix #202 .

### CODE REVIEW

**Comment by johanneskastl** [comment]
Any update on this one? Could this be merged and a release tagged to fix the builds for openSUSE?

**Comment by johanneskastl** [comment]
> Any update on this one? Could this be merged and a release tagged to fix the builds for openSUSE?

?

**Comment by norwoodj** [comment]
I don't believe this is necessary anymore with the recent update to go1.22

**Comment by johanneskastl** [comment]
> I don't believe this is necessary anymore with the recent update to go1.22

Sorry to disappoint you, but at least the issue in #202 is still happening, even with go1.22

**Comment by norwoodj** [comment]
Will you try on the latest master? I just released v1.13.0. I tested in docker:
```
FROM opensuse/leap:15

RUN zypper refresh && zypper --non-interactive in go1.22
```

I am then able to successfully build with:
```
go build -buildmode=pie -o bin/helm-docs ./cmd/helm-docs   
```

It fails if I pass `-mod=vendor` as you do, because we don't vendor the dependencies for this project. Without that, however, this does indeed pass.

**Comment by johanneskastl** [comment]
Hooray! I can confirm, that 1.13.0 builds successfully! Thanks a lot!

**Pull request closed without merging**
