### PR TITLE
Proposal to add custom notation type

### PR DESCRIPTION
**Pull request by lucernae**
As a reference to the issue #86,

I attached my PR here for review and consideration.

### CODE REVIEW

**Comment by lucernae** [comment]
I attached a sample generated [README.md](https://github.com/lucernae/helm-docs/blob/notation-type/example-charts/custom-value-notation-type/README.md) It has to be viewed from my branch so Github can render it as usual.

**Comment by lucernae** [comment]
Seems I failed the original unittest. I will try to understand the case by generating from the yaml

**Comment by lucernae** [comment]
Hi, do you have some comments on this?

**Comment by norwoodj** [comment]
Apologies for being so slow to look at this. I am going to try to take a look at this soon, it is just hard to find the time between life and my real job.

**Comment by norwoodj** [comment]
I took a look at this today. I think this is maybe something worth incorporating, but I'm having trouble understanding what the intended use case is. I think it would help me both understand better and save me some future work if you documented the new features you're adding in the project README.

Beyond that, I have a couple of requests:
* Please rebase and fix merge conflicts
* Squash your changes into a single commit.

Thanks again for all the work you've put into this, I do want to merge these changes, I'm just not yet sure I understand how it would be used.

**Comment by lucernae** [comment]
Hi @norwoodj , thanks for looking at it. Sorry for the late reply, I've been on holiday. I'm going check the recent conflicts first to make sure it is up to date with master, then I will ping you again when it is ready for review.

**Comment by lucernae** [comment]
It doesn't seem the push triggers the CI. I'm going to close this PR and reopen, so that GH actions will be triggered on reopen.

**Comment by lucernae** [comment]
Ok, these are the changes:
- [x] Please rebase and fix merge conflicts
- [x] Squash your changes into a single commit.
- [x] Tested unittest in `pkg/document`
- [x] Showcase the usage of `@notationType` metadata and custom rendering in [example-charts/custom-value-notation-type/README.md](https://github.com/lucernae/helm-docs/blob/notation-type/example-charts/custom-value-notation-type/README.md). I think this is the best place to see what kind of improvements I want to bring.
- [x] Added sections for custom rendering in [README.md](https://github.com/lucernae/helm-docs/blob/notation-type/README.md#advanced-table-rendering)
- [x] Added built-int template to render HTML tables in [README.md](https://github.com/lucernae/helm-docs/blob/notation-type/README.md#markdown-rendering)

**Review by norwoodj — APPROVED** [review]

**Pull request merged**
