### PR TITLE
chore: slightly changes format of @default values as they're rendered…

### PR DESCRIPTION
**Pull request by norwoodj**
… in the mardown output

### CODE REVIEW

**Comment by eddycharly** [comment]
@norwoodj any specific reason why you changed the the format ?
Not using any formatting allowed me to inject things like links in the column.

Now it appears as code :(

image

**Comment by norwoodj** [comment]
Ugh. My thinking was that I'd like to have things rendered the same as when the defaults are pulled from the values.yaml file. See https://github.com/norwoodj/helm-docs/tree/master/example-charts/custom-template#chart-values, where the `@default`-specified default appears the same as the others.

I see now that I broke you though. I really like the ability to treat these specified defaults the same in output. Would you be okay if I added a second way of specifying this, e.g.:

```
value:
# value.example -- description
# @defaultNote -- See [values.yaml](./values.yaml)
```
?

I know you'll have to change your charts, but it would enable users to get both behaviours, and I think that defaultNote is a better descriptor of what you're using this for.
example: ""

**Comment by eddycharly** [comment]
I'm not sure when one wants to specify a custom default that is not the real default and wants it to be rendered with formatting.

I mean, when using the custom default, it's probably that we want to provide a link or a short text explaining how the default is computed rather than some code, not sure how formatting applies in this case.

Anyway, i will be more than happy if you implement it with defaultNote and no problems with changing my charts.

Thanks.

**Comment by norwoodj** [comment]
You make a good point. Obviously if you're going to do what I did, you could just put the value in the values.yaml directly. Duh

I'll change it back so that default renders without tick quoting. Thanks for pointing this out. I'll get to it this afternoon. Sorry for the inconvenience.

**Comment by eddycharly** [comment]
Awesome, thanks.
👍

**Pull request merged**
