### PR TITLE
feat: add toYaml and fromYaml to functions map

### PR DESCRIPTION
**Pull request by jasondamour**
Adds `toYaml` and `fromYaml` functions from helm src

### CODE REVIEW

**Comment by johanneskastl** [comment]
I would love to see those functions, as they were used a lot by the k8s-at-home guys in their charts (which are deprecated, so I forked some and noticed the missing functions...)

**Comment by gabe565** [comment]
This would be amazing. There's also a PR to add this in Masterminds/sprig#360

**Comment by jasondamour** [comment]
@Nepo26 Need anything from me to move this?

**Comment by Nepo26** [comment]
Honestly, only chart examples in the `example-charts` folder and test cases for automated testing. Any question you may ping me.

**Comment by norwoodj** [comment]
@jasondamour Agreeing with @Nepo26, if you add an example chart that uses these, and a test case, we'll merge.

**Comment by ebuildy** [comment]
hello, this look fantastic, may I help?

**Comment by ebuildy** [comment]
I love you :-)

I can add an example and some tests, here my readme_template, to display storage class:

```
{{ $values := (.Files.Get "values.yaml") | fromYaml }}

## Snapshot classes

| name     | resource group | incremental |
|----------|----------------|-------------|
{{- range $name, $spec := $values.volumeSnapshotClass }}
{{- range $parameterIncr := list "true" "false" }}
| {{ $name }}{{- if eq $parameterIncr "true" -}}-incr{{- end }} | {{ $parameterIncr }} | {{ $spec.parameters.resourceGroup | default "" }} |
{{- end }}
{{- end }}
```

This work like a charm!

**Comment by ebuildy** [comment]
hello @norwoodj , I have added basic example on PR https://github.com/norwoodj/helm-docs/pull/230

**Comment by norwoodj** [comment]
I'm confused, you've added examples, but not the code from this PR. Did you generate the README in the example you included using the version of helm-docs from this PR?

**Comment by ebuildy** [comment]
> I'm confused, you've added examples, but not the code from this PR. Did you generate the README in the example you included using the version of helm-docs from this PR?

yes exactly! I dont have write access to this PR fork, to avoid a PR of PR ^^ I prefer create the PR here.

**Pull request merged**
